acq: ei
ard: True
n_init: 20 # USUALLY 20 but 5 for debug
max_iters: 200
min_cuda: 10
device: 'cuda'
seq_len: 11
normalise: True
batch_size: 1
save_path: '/home/alexc/antigenbinding/results/BO_hebo_transformed_overlap'
kernel_type: 'transformed_overlap' #transformed_overlap ssk
noise_variance: 1e-6
resume: ???
search_strategy: 'glocal' # local (CASMO) or glocal (HEBO variant)

bbox:
  tool: Absolut
  path: '/mnt/data/alexc/Absolut3/'
  process: 18
  startTask: 1
