acq: ei
ard: True
n_init: 20
max_iters: 200
min_cuda: 10
device: 'cuda'
seq_len: 11
normalise: True
batch_size: 1
save_path: '/home/alexc/antigenbinding/results/BO_hebo_ssk'
kernel_type: 'ssk' #transformed_overlap ssk
noise_variance: 1e-6
resume: ???
search_strategy: 'glocal' # local (CASMO) or glocal (HEBO variant)

bbox:
  tool: Absolut
  path: '/mnt/data/alexc/Absolut2/'
  process: 18
  startTask: 1
